In [17]:
import metpy.calc as mpcalc
from metpy.units import units
import iris
import numpy as np
import sys
sys.path.append('/pf/b/b381639/Analysis')
import fxtian_function as fx
from iris.time import PartialDateTime
import datetime
import cf_units
import iris.coord_categorisation
import iris.quickplot as qplt
import matplotlib.pyplot as plt
import numpy as np
import xarray as xr
import metpy.calc as mpcalc

###############
# plot ERA5
###############

f1='/work/bb1153/b381639/NorESM/QREFHT_150_tropical_ocean.nc'
f2='/work/bb1153/b381639/NorESM/PS_0150_tropical_ocean.nc'
f3='/work/bb1153/b381639/NorESM/SST_150_tropical_ocean.nc'
fQ=xr.open_dataset(f1)
fP=xr.open_dataset(f2)
fSST=xr.open_dataset(f3)
Q=fQ.QREFHT # kg/kg
P=fP.PS
SST=fSST.SST - 273.15 # T in degrees Celsius:



Q=Q*units('kg/kg')
pressure=P*units.Pa
sst=SST*units.degC

In [21]:
SST

<xarray.DataArray 'SST' (time: 365, latitude: 80, longitude: 720)>
array([[[  19.51278371,   19.47059372,   19.55394766, ...,
           20.22528228,   19.73107649,   19.53356856],
        [  19.65821883,   19.61127873,   19.56596205, ...,
           20.39294943,   19.99845233,   19.74493554],
        [  19.9112608 ,   20.04571134,   19.95505356, ...,
           20.35407188,   20.10102008,   19.85433168],
        ...,
        [-273.15      , -273.15      , -273.15      , ...,
         -273.15      , -273.15      , -273.15      ],
        [-273.15      , -273.15      , -273.15      , ...,
         -273.15      , -273.15      , -273.15      ],
        [-273.15      , -273.15      , -273.15      , ...,
         -273.15      , -273.15      , -273.15      ]],

       [[  19.63813698,   19.55492866,   19.59821577, ...,
           20.29737072,   19.81716092,   19.66225358],
        [  19.80480218,   19.72843942,   19.62789146, ...,
           20.46424069,   20.07075264,   19.86612556],
        [  19.97470656,   20.10699402,   19.97450436, ...,
           20.42542792,   20.14531524,   19.91054115],
...
        [-273.15      , -273.15      , -273.15      , ...,
         -273.15      , -273.15      , -273.15      ],
        [-273.15      , -273.15      , -273.15      , ...,
         -273.15      , -273.15      , -273.15      ],
        [-273.15      , -273.15      , -273.15      , ...,
         -273.15      , -273.15      , -273.15      ]],

       [[  20.58661657,   20.50780592,   20.34669637, ...,
           20.40125147,   20.54807809,   20.54201075],
        [  20.72157647,   20.60067469,   20.42335691, ...,
           20.27477394,   20.45645788,   20.62430084],
        [  20.73721754,   20.59122656,   20.469485  , ...,
           20.33972563,   20.43462704,   20.69279332],
        ...,
        [-273.15      , -273.15      , -273.15      , ...,
         -273.15      , -273.15      , -273.15      ],
        [-273.15      , -273.15      , -273.15      , ...,
         -273.15      , -273.15      , -273.15      ],
        [-273.15      , -273.15      , -273.15      , ...,
         -273.15      , -273.15      , -273.15      ]]])
Coordinates:
  * time       (time) object 0150-01-01 00:00:00 ... 0150-12-31 00:00:00
  * longitude  (longitude) float64 0.25 0.75 1.25 1.75 ... 358.8 359.2 359.8
  * latitude   (latitude) float64 -19.75 -19.25 -18.75 ... 18.75 19.25 19.75

In [18]:
Ms=mpcalc.saturation_mixing_ratio(pressure, sst)
Qs=mpcalc.specific_humidity_from_mixing_ratio(Ms)


In [19]:
DQ=Qs-Q

In [20]:
DQ

<xarray.DataArray (time: 365, latitude: 80, longitude: 720)>
<Quantity([[[0.00306149 0.00299016 0.00302489 ... 0.00390479 0.00335316 0.00311932]
  [0.00321428 0.0031272  0.0030778  ... 0.00409001 0.00365671 0.00336935]
  [0.00340838 0.00350959 0.00343565 ... 0.00398226 0.00370017 0.00341236]
  ...
  [       nan        nan        nan ...        nan        nan        nan]
  [       nan        nan        nan ...        nan        nan        nan]
  [       nan        nan        nan ...        nan        nan        nan]]

 [[0.0029503  0.00283185 0.00284101 ... 0.00364541 0.00314367 0.00298125]
  [0.00312797 0.00300079 0.00285359 ... 0.00387758 0.00346732 0.00323439]
  [0.00330958 0.00337191 0.00315183 ... 0.00383276 0.00354652 0.00328474]
  ...
  [       nan        nan        nan ...        nan        nan        nan]
  [       nan        nan        nan ...        nan        nan        nan]
  [       nan        nan        nan ...        nan        nan        nan]]

 [[0.00319594 0.00313872 0.00313665 ... 0.00370392 0.0032883  0.00317174]
  [0.00338463 0.00334128 0.00320316 ... 0.00385385 0.00353871 0.00338868]
  [0.00364413 0.00371231 0.00343261 ... 0.0038793  0.00366779 0.0035232 ]
  ...
...
  ...
  [       nan        nan        nan ...        nan        nan        nan]
  [       nan        nan        nan ...        nan        nan        nan]
  [       nan        nan        nan ...        nan        nan        nan]]

 [[0.0036944  0.0036105  0.00344742 ... 0.00335281 0.00348818 0.00354821]
  [0.00372945 0.00359485 0.00342113 ... 0.00318047 0.00335848 0.00356988]
  [0.00364763 0.00350197 0.00338764 ... 0.0032371  0.0033614  0.00359764]
  ...
  [       nan        nan        nan ...        nan        nan        nan]
  [       nan        nan        nan ...        nan        nan        nan]
  [       nan        nan        nan ...        nan        nan        nan]]

 [[0.00389058 0.00387381 0.00381675 ... 0.00377967 0.00382755 0.00379732]
  [0.00400165 0.00399133 0.00395348 ... 0.00357337 0.00368288 0.00383581]
  [0.00404745 0.00404241 0.00407617 ... 0.00352767 0.00361859 0.00390306]
  ...
  [       nan        nan        nan ...        nan        nan        nan]
  [       nan        nan        nan ...        nan        nan        nan]
  [       nan        nan        nan ...        nan        nan        nan]]], 'dimensionless')>
Coordinates:
  * time       (time) object 0150-01-01 00:00:00 ... 0150-12-31 00:00:00
  * longitude  (longitude) float64 0.25 0.75 1.25 1.75 ... 358.8 359.2 359.8
  * latitude   (latitude) float64 -19.75 -19.25 -18.75 ... 18.75 19.25 19.75

In [16]:


DQ.to_netcdf("/work/bb1153/b381639/ERA5/DQ_daily_NorESM.nc")

In [69]:
Es=xr.zeros_like(T)

In [70]:
Es.data =  611.2 * np.exp(17.67*T.data/(T.data + 243.5)) # Es in pasca T in celsius

In [71]:
Es[100,:,50].data

array([      nan,       nan,       nan,       nan,       nan,       nan,
             nan,       nan,       nan,       nan,       nan,       nan,
             nan,       nan,       nan,       nan,       nan,       nan,
             nan,       nan,       nan,       nan,       nan,       nan,
             nan,       nan,       nan,       nan,       nan,       nan,
             nan,       nan,       nan,       nan,       nan,       nan,
             nan,       nan,       nan,       nan,       nan,       nan,
             nan,       nan,       nan,       nan,       nan,       nan,
             nan,       nan,       nan,       nan,       nan,       nan,
             nan,       nan,       nan,       nan,       nan,       nan,
             nan,       nan,       nan,       nan,       nan,       nan,
             nan,       nan,       nan,       nan,       nan,       nan,
             nan,       nan,       nan,       nan,       nan,       nan,
             nan,       nan,       nan,       nan, 

In [72]:
Qs=xr.zeros_like(T)

In [75]:
Qs.data=0.622*Es/P # Qs in kg/kg

In [74]:
Qs[100,:,50].data

array([       nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        

In [76]:
import numpy as np
class sounding_df:
    
    def __init__(self, df):
        # this __init__ method is used to create new objects inside the class
        self.p = np.array(df['Pressure'])
        self.temp = np.array(df['Temp']) # in Kelvin
        self.dew = np.array(df['Dewpt']) # in Kelvin
        
    def spec_humidity(self, latent='water'):
        """Calculates SH automatically from the dewpt. Returns in g/kg"""
        # Declaring constants
        self.e0 = 6.113 # saturation vapor pressure in hPa
        # e0 and Pressure have to be in same units
        self.c_water = 5423 # L/R for water in Kelvin
        self.c_ice = 6139 # L/R for ice in Kelvin
        self.T0 = 273.15 # Kelvin
        
        if latent == 'water' or latent == 'Water':
            self.c = self.c_water    # using c for water
        
        else:
            self.c= self.c_ice       # using c_ice for ice, clear state
        
        # saturation vapor not required, uncomment to calculate it (units in hPa becuase of e0)
        #sat_vapor = self.e0 * np.exp((self.c * (self.temp -self.T0))/(self.temp * self.T0)) 
        
        #calculating specific humidity, q directly from dew point temperature
        #using equation 4.24, Pg 96 Practical Meteorolgy (Roland Stull)
#        self.q = (622 * self.e0 * np.exp(self.c * (self.dew - self.T0)/(self.dew * self.T0)))/self.p # g/kg 
        self.q = (622 * self.e0/self.p) * np.exp(self.c * (self.dew - self.T0)/(self.dew * self.T0))
        # 622 is the ratio of Rd/Rv in g/kg
        # where q in the unit of g/kg, e0 and p in the same unit in order to be cancelled out, c, dew and T0 in the unit of K
        return self.q