In [15]:
import metpy.calc as mpcalc
from metpy.units import units
import iris
import numpy as np
import sys
sys.path.append('/pf/b/b381639/Analysis')
import fxtian_function as fx
from iris.time import PartialDateTime
import datetime
import cf_units
import iris.coord_categorisation
import iris.quickplot as qplt
import matplotlib.pyplot as plt
import numpy as np
import xarray as xr
import metpy.calc as mpcalc

###############
# plot ERA5
###############

f1='/work/bb1153/b381639/NorESM/betzy_Hcam5_1.cam.h1.0010-01-01-00000.nc'

fQ=xr.open_dataset(f1)

Q=fQ.QREFHT # kg/kg
P=fQ.PSL
SST=fQ.SST - 273.15 # T in degrees Celsius:

Q=Q*units('kg/kg')
pressure=P*units.Pa
sst=SST*units.degC

In [16]:
Ms=mpcalc.saturation_mixing_ratio(pressure, sst)
Qs=mpcalc.specific_humidity_from_mixing_ratio(Ms)


In [17]:
DQ=Qs-Q

In [18]:
DQ

<xarray.DataArray (time: 365, lat: 768, lon: 1152)>
<Quantity([[[0.00302779 0.00302791 0.00302791 ... 0.00302779 0.00302779 0.00302779]
  [0.00302603 0.00302614 0.00302625 ... 0.00302591 0.00302608 0.00302611]
  [0.00301919 0.00301919 0.00301941 ... 0.00301911 0.00301921 0.00301923]
  ...
  [0.00320705 0.00320692 0.00320726 ... 0.00320705 0.00320717 0.00320701]
  [0.0032029  0.00320308 0.00320289 ... 0.00320289 0.00320305 0.00320304]
  [0.00320166 0.00320168 0.00320169 ... 0.00320163 0.00320163 0.00320164]]

 [[0.00297871 0.00297876 0.00297876 ... 0.00297871 0.00297871 0.00297871]
  [0.00297014 0.00296976 0.00296957 ... 0.00296895 0.00296985 0.00296848]
  [0.00297801 0.0029771  0.00297585 ... 0.00297862 0.00297672 0.00297662]
  ...
  [0.0031767  0.00317673 0.00317709 ... 0.00317644 0.00317697 0.00317675]
  [0.00317471 0.00317463 0.00317464 ... 0.00317451 0.00317517 0.00317489]
  [0.00317355 0.00317357 0.00317358 ... 0.00317352 0.00317352 0.00317353]]

 [[0.0029735  0.00297351 0.00297351 ... 0.0029735  0.0029735  0.0029735 ]
  [0.00296952 0.00297102 0.00297262 ... 0.0029719  0.00297117 0.00296872]
  [0.0029865  0.0029842  0.00298591 ... 0.00298657 0.00298541 0.0029855 ]
  ...
...
  ...
  [0.00283903 0.00283975 0.0028387  ... 0.00284007 0.00283883 0.00283838]
  [0.00285601 0.00285727 0.00285716 ... 0.00285724 0.00285662 0.00285682]
  [0.00286356 0.0028636  0.00286362 ... 0.00286351 0.00286351 0.00286353]]

 [[0.00312757 0.00312757 0.00312757 ... 0.00312757 0.00312757 0.00312757]
  [0.00312564 0.00312569 0.00312567 ... 0.00312566 0.00312568 0.00312566]
  [0.00312174 0.00312165 0.00312161 ... 0.00312186 0.00312182 0.00312176]
  ...
  [0.00302549 0.00302545 0.00302539 ... 0.00302576 0.00302552 0.00302536]
  [0.00302192 0.00302188 0.003022   ... 0.00302211 0.00302207 0.00302207]
  [0.00301882 0.00301885 0.00301886 ... 0.00301878 0.00301878 0.0030188 ]]

 [[0.00310865 0.00310865 0.00310865 ... 0.00310865 0.00310865 0.00310865]
  [0.00310095 0.003101   0.00310099 ... 0.00310097 0.00310099 0.00310096]
  [0.00309754 0.0030974  0.0030973  ... 0.00309778 0.00309768 0.00309758]
  ...
  [0.00305987 0.0030598  0.00305987 ... 0.00306011 0.00305998 0.00306   ]
  [0.00306378 0.00306374 0.00306382 ... 0.00306403 0.00306392 0.00306382]
  [0.00306805 0.00306807 0.00306808 ... 0.00306801 0.00306801 0.00306803]]], 'dimensionless')>
Coordinates:
  * time     (time) object 0010-01-01 00:00:00 ... 0010-12-31 00:00:00
  * lat      (lat) float64 -90.0 -89.77 -89.53 -89.3 ... 89.3 89.53 89.77 90.0
  * lon      (lon) float64 0.0 0.3125 0.625 0.9375 ... 358.8 359.1 359.4 359.7

In [19]:


DQ.to_netcdf("/work/bb1153/b381639/NorESM/DQ_daily_HCAM5.nc")

In [69]:
Es=xr.zeros_like(T)

In [70]:
Es.data =  611.2 * np.exp(17.67*T.data/(T.data + 243.5)) # Es in pasca T in celsius

In [71]:
Es[100,:,50].data

array([      nan,       nan,       nan,       nan,       nan,       nan,
             nan,       nan,       nan,       nan,       nan,       nan,
             nan,       nan,       nan,       nan,       nan,       nan,
             nan,       nan,       nan,       nan,       nan,       nan,
             nan,       nan,       nan,       nan,       nan,       nan,
             nan,       nan,       nan,       nan,       nan,       nan,
             nan,       nan,       nan,       nan,       nan,       nan,
             nan,       nan,       nan,       nan,       nan,       nan,
             nan,       nan,       nan,       nan,       nan,       nan,
             nan,       nan,       nan,       nan,       nan,       nan,
             nan,       nan,       nan,       nan,       nan,       nan,
             nan,       nan,       nan,       nan,       nan,       nan,
             nan,       nan,       nan,       nan,       nan,       nan,
             nan,       nan,       nan,       nan, 

In [72]:
Qs=xr.zeros_like(T)

In [75]:
Qs.data=0.622*Es/P # Qs in kg/kg

In [74]:
Qs[100,:,50].data

array([       nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        

In [76]:
import numpy as np
class sounding_df:
    
    def __init__(self, df):
        # this __init__ method is used to create new objects inside the class
        self.p = np.array(df['Pressure'])
        self.temp = np.array(df['Temp']) # in Kelvin
        self.dew = np.array(df['Dewpt']) # in Kelvin
        
    def spec_humidity(self, latent='water'):
        """Calculates SH automatically from the dewpt. Returns in g/kg"""
        # Declaring constants
        self.e0 = 6.113 # saturation vapor pressure in hPa
        # e0 and Pressure have to be in same units
        self.c_water = 5423 # L/R for water in Kelvin
        self.c_ice = 6139 # L/R for ice in Kelvin
        self.T0 = 273.15 # Kelvin
        
        if latent == 'water' or latent == 'Water':
            self.c = self.c_water    # using c for water
        
        else:
            self.c= self.c_ice       # using c_ice for ice, clear state
        
        # saturation vapor not required, uncomment to calculate it (units in hPa becuase of e0)
        #sat_vapor = self.e0 * np.exp((self.c * (self.temp -self.T0))/(self.temp * self.T0)) 
        
        #calculating specific humidity, q directly from dew point temperature
        #using equation 4.24, Pg 96 Practical Meteorolgy (Roland Stull)
#        self.q = (622 * self.e0 * np.exp(self.c * (self.dew - self.T0)/(self.dew * self.T0)))/self.p # g/kg 
        self.q = (622 * self.e0/self.p) * np.exp(self.c * (self.dew - self.T0)/(self.dew * self.T0))
        # 622 is the ratio of Rd/Rv in g/kg
        # where q in the unit of g/kg, e0 and p in the same unit in order to be cancelled out, c, dew and T0 in the unit of K
        return self.q