In [9]:
import metpy.calc as mpcalc
from metpy.units import units
import iris
import numpy as np
import sys
sys.path.append('/pf/b/b381639/Analysis')
import fxtian_function as fx
from iris.time import PartialDateTime
import datetime
import cf_units
import iris.coord_categorisation
import iris.quickplot as qplt
import matplotlib.pyplot as plt
import numpy as np
import xarray as xr
import metpy.calc as mpcalc

###############
# plot ERA5
###############


f='/work/bb1153/b381639/NorESM/DQbias_150_daily_tropical_ocean.nc'

fE=xr.open_dataset(f1)

DQB=fE.__xarray_dataarray_variable__


In [10]:
def interpolate_x(cube,save=None):
    import iris
    import iris.coord_categorisation
    target_lon = iris.coords.DimCoord(np.linspace(0,360,720),standard_name='longitude',units='degrees')
    target_lat = iris.coords.DimCoord(np.linspace(-20,20,80),standard_name='latitude',units='degrees',circular=True)
    target_cube = iris.cube.Cube(np.zeros((80,720),np.float32),dim_coords_and_dims=[(target_lat,0),(target_lon,1)])
    try:
        cube.coord('longitude').guess_bounds()
    except:
        pass
    try:
        cube.coord('latitude').guess_bounds()
    except:
        pass
    target_cube.coord('longitude').guess_bounds()
    target_cube.coord('latitude').guess_bounds()
    scheme = iris.analysis.AreaWeighted(mdtol=0)
    interp_cube = cube.regrid(target_cube,scheme)

    if save is not None:
        iris.save(interp_cube,save)
    return(interp_cube)

In [7]:
cube_era5=interpolate_x(DQE[0,:,:])

AttributeError: 'DataArray' object has no attribute 'regrid'

In [24]:
fw='/work/bb1153/b381639/ERA5/wsp10_daymean_2020_tropical_ocean.nc'
fW=xr.open_dataset(fw)
W10=fW.wsp10
Varout=xr.zeros_like(W10).rename('wsp10dq')

In [25]:
WQ=W10*DQ

Varout.data=WQ.data

Varout.attrs['name']='W10DQ'
Varout.attrs['shortName']='wsp10dq'
Varout.attrs['cfVarName']='wsp10dq'

In [29]:
Varout

<xarray.DataArray 'wsp10dq' (time: 366, latitude: 161, longitude: 1440)>
<Quantity([[[       nan        nan        nan ...        nan        nan        nan]
  [       nan        nan        nan ...        nan        nan        nan]
  [       nan        nan        nan ...        nan        nan        nan]
  ...
  [0.03065872 0.03105539 0.0324253  ... 0.0311134  0.03073944 0.03033188]
  [0.03173355 0.03172035 0.03221988 ... 0.03273557 0.03231581 0.03167173]
  [0.03313201 0.03279194 0.03283538 ... 0.03473057 0.03441055 0.03391808]]

 [[       nan        nan        nan ...        nan        nan        nan]
  [       nan        nan        nan ...        nan        nan        nan]
  [       nan        nan        nan ...        nan        nan        nan]
  ...
  [0.03763264 0.0383218  0.0388701  ... 0.03760599 0.03685926 0.03667375]
  [0.03899334 0.03952089 0.03930145 ... 0.03906901 0.03885797 0.03826824]
  [0.04023832 0.04034485 0.04004318 ... 0.04078415 0.04080209 0.04023646]]

 [[       nan        nan        nan ...        nan        nan        nan]
  [       nan        nan        nan ...        nan        nan        nan]
  [       nan        nan        nan ...        nan        nan        nan]
  ...
...
  ...
  [0.02114155 0.02103131 0.02123376 ... 0.02213827 0.02191941 0.02143616]
  [0.02108937 0.02130612 0.02121326 ... 0.02134058 0.02157851 0.02126831]
  [0.02155785 0.0217873  0.02168827 ... 0.02105087 0.02137596 0.02163109]]

 [[       nan        nan        nan ...        nan        nan        nan]
  [       nan        nan        nan ...        nan        nan        nan]
  [       nan        nan        nan ...        nan        nan        nan]
  ...
  [0.02959411 0.02910082 0.02880779 ... 0.0293883  0.02976311 0.02972607]
  [0.02958797 0.0298328  0.02948899 ... 0.02844146 0.02905897 0.02895082]
  [0.03000215 0.03032926 0.03060461 ... 0.02775539 0.02837229 0.02926323]]

 [[       nan        nan        nan ...        nan        nan        nan]
  [       nan        nan        nan ...        nan        nan        nan]
  [       nan        nan        nan ...        nan        nan        nan]
  ...
  [0.03093376 0.03041335 0.02968241 ... 0.03209263 0.03231313 0.03174716]
  [0.0314551  0.03110913 0.03079847 ... 0.03191099 0.03207857 0.03166443]
  [0.03277245 0.03204213 0.0317768  ... 0.03264645 0.03275559 0.03290924]]], 'dimensionless')>
Coordinates:
  * time       (time) datetime64[ns] 2020-01-01T09:00:00 ... 2020-12-31T09:00:00
  * longitude  (longitude) float32 0.0 0.25 0.5 0.75 ... 359.0 359.2 359.5 359.8
  * latitude   (latitude) float32 20.0 19.75 19.5 19.25 ... -19.5 -19.75 -20.0
Attributes:
    cell_methods:  time: mean
    name:          W10DQ
    shortName:     wsp10dq
    cfVarName:     wsp10dq

In [31]:
Varout.to_netcdf("/work/bb1153/b381639/ERA5/W10DQ_daily_ERA5.nc")

In [69]:
Es=xr.zeros_like(T)

In [70]:
Es.data =  611.2 * np.exp(17.67*T.data/(T.data + 243.5)) # Es in pasca T in celsius

In [71]:
Es[100,:,50].data

array([      nan,       nan,       nan,       nan,       nan,       nan,
             nan,       nan,       nan,       nan,       nan,       nan,
             nan,       nan,       nan,       nan,       nan,       nan,
             nan,       nan,       nan,       nan,       nan,       nan,
             nan,       nan,       nan,       nan,       nan,       nan,
             nan,       nan,       nan,       nan,       nan,       nan,
             nan,       nan,       nan,       nan,       nan,       nan,
             nan,       nan,       nan,       nan,       nan,       nan,
             nan,       nan,       nan,       nan,       nan,       nan,
             nan,       nan,       nan,       nan,       nan,       nan,
             nan,       nan,       nan,       nan,       nan,       nan,
             nan,       nan,       nan,       nan,       nan,       nan,
             nan,       nan,       nan,       nan,       nan,       nan,
             nan,       nan,       nan,       nan, 

In [72]:
Qs=xr.zeros_like(T)

In [75]:
Qs.data=0.622*Es/P # Qs in kg/kg

In [74]:
Qs[100,:,50].data

array([       nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        

In [76]:
import numpy as np
class sounding_df:
    
    def __init__(self, df):
        # this __init__ method is used to create new objects inside the class
        self.p = np.array(df['Pressure'])
        self.temp = np.array(df['Temp']) # in Kelvin
        self.dew = np.array(df['Dewpt']) # in Kelvin
        
    def spec_humidity(self, latent='water'):
        """Calculates SH automatically from the dewpt. Returns in g/kg"""
        # Declaring constants
        self.e0 = 6.113 # saturation vapor pressure in hPa
        # e0 and Pressure have to be in same units
        self.c_water = 5423 # L/R for water in Kelvin
        self.c_ice = 6139 # L/R for ice in Kelvin
        self.T0 = 273.15 # Kelvin
        
        if latent == 'water' or latent == 'Water':
            self.c = self.c_water    # using c for water
        
        else:
            self.c= self.c_ice       # using c_ice for ice, clear state
        
        # saturation vapor not required, uncomment to calculate it (units in hPa becuase of e0)
        #sat_vapor = self.e0 * np.exp((self.c * (self.temp -self.T0))/(self.temp * self.T0)) 
        
        #calculating specific humidity, q directly from dew point temperature
        #using equation 4.24, Pg 96 Practical Meteorolgy (Roland Stull)
#        self.q = (622 * self.e0 * np.exp(self.c * (self.dew - self.T0)/(self.dew * self.T0)))/self.p # g/kg 
        self.q = (622 * self.e0/self.p) * np.exp(self.c * (self.dew - self.T0)/(self.dew * self.T0))
        # 622 is the ratio of Rd/Rv in g/kg
        # where q in the unit of g/kg, e0 and p in the same unit in order to be cancelled out, c, dew and T0 in the unit of K
        return self.q